- action:
  - data:
      message: Turned on TP Link Switch
      title: Notification
    service: notify.pb
  alias: Automation 1
  condition: []
  id: '1518818563466'
  trigger:
  - at: '17:00'
    platform: time
