homeassistant:
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 200
  name: Home
  unit_system: imperial
  time_zone: America/Chicago
  temperature_unit: F
  customize: !include customize.yaml

config:

hassio:

# automation:
  # - alias: LogController
    # action:
      # service: recorder_purge
    # data:
      # keep_days: 4
    # trigger:
      # platform: time
      # Matches every hour at 5 minutes past whole
      # hours: 24
      # minutes: 00
      # seconds: 00
    # hide_entity: True
    # initial_state: True

automation: !include automations.yaml

http:
  api_password: !secret http_password
  base_url: http://dhahaj.duckdns.org:8123/
  #use_x_forwarded_for: True
  
recorder:
  purge_keep_days: 5

#discovery:

shopping_list:

updater:
  include_used_components: true

history:

#logger:
#  default: warning

#python_scripts:

logbook: !include logbook.yaml

#arduino:

frontend:
  themes:
    greeny:
      primary-color: green
    black:
      primary-color: black
    bluesky:
      primary-color: blue
    purple:
      primary-color: purple
 
coinbase:
  api_key: WZOKwtzSfHPa8ujD
  api_secret: dKKtwAKvkg8hxxT4MxCayqR6j1RCypTm
  exchange_rate_currencies:
    - BTC
    - ETH
    - LTC
    #- USD

sun:

map:

zone: !include zones.yaml

device_tracker:
  - platform: gpslogger
    icon: mdi:android
    password: !secret gpspass

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio:3218
  ide:
    title: IDE
    icon: mdi:code-braces
    url: http://127.0.0.1:80

notify:
  - platform: pushbullet
    name: pb
    api_key: !secret pushbullet_api

switch: 
  - platform: tplink
    host: 192.168.0.58
    name: TPLink
    icon: mdi:lamp
#  - platform: broadlink
   # host: 192.168.0.225
    #mac: '34:ea:34:58:b9:5c'
    #friendly_name: RM Mini3
    #type: rm_mini
    #switches:
      
camera:
  - platform: rpi_camera
    name: RaspberryPi Cam
    vertical_flip: 1
    horizontal_flip: 1
    image_quality: 5
    #file_path: /tmp/camera.jpg
    
weblink:
  entities:
    - name: Remote Home Router
      url: https://75.1.37.24:21747/
    - name: HomeAssistant.io
      url: https://home-assistant.io
    - name: NodeMCU
      url: http://dhahaj.duckdns.org:8888/
