homeassistant:
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 200
  name: Home
  unit_system: imperial
  time_zone: America/Chicago
  temperature_unit: F
  customize: !include customize.yaml

hassio:

config:

#automations: !include automations.yaml

http:
  api_password: !secret http_password
  base_url: http://dhahaj.duckdns.org:8123/
  use_x_forwarded_for: True
  
#recorder:
#  purge_days: 4

#discovery:

#shopping_list:

updater:
  include_used_components: true

logbook:

history:        

logger:
  default: warning

#python_scripts:
        

logbook: !include logbook.yaml

#arduino:

frontend:
  themes:
    greeny:
      primary-color: green
    black:
      primary-color: black
    bluesky:
      primary-color: blue
    purple:
      primary-color: purple
 
coinbase:
  api_key: WZOKwtzSfHPa8ujD
  api_secret: dKKtwAKvkg8hxxT4MxCayqR6j1RCypTm
  exchange_rate_currencies:
    - BTC
    - ETH
    - LTC
    #- USD

sun:

map:

zone: !include zones.yaml

device_tracker:
  - platform: gpslogger
    password: !secret gpspass

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio:3218
  ide:
    title: IDE
    icon: mdi:code-braces
    url: http://192.168.0.194:8321
    
notify:
  - platform: pushbullet
    name: pb
    api_key: !secret pushbullet_api

switch: 
  - platform: tplink
    host: 192.168.0.58
    name: TPLink
    icon: mdi:lamp
    
camera:
  - platform: rpi_camera
    name: RaspberryPi Cam
    vertical_flip: 1
    horizontal_flip: 1
    image_quality: 7
    file_path: /tmp/camera.jpg
    
weblink:
  entities:
    - name: Remote Home Router
      url: https://75.1.37.24:21747/
    - name: HomeAssistant.io
      url: https://home-assistant.io
    - name: NodeMCU
      url: http://dhahaj.duckdns.org:8888/
