homeassistant:
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 200
  name: Home
  unit_system: imperial
  time_zone: America/Chicago
  temperature_unit: F
  customize: !include customize.yaml

config:

hassio:

automation: !include automations.yaml

http:
  api_password: !secret http_password
  base_url: http://dhahaj.duckdns.org:8123/
  use_x_forwarded_for: True

sensor:
  platform: example

recorder:
  purge_keep_days: 4

#discovery:

# shopping_list:

updater:
  include_used_components: true

history:

logger:
  default: error
  logs:
    homeassistant.components.switch.hook: debug

# logbook: !include logbook.yaml

frontend:
  themes:
    greeny:
      primary-color: green
    black:
      primary-color: black
    bluesky:
      primary-color: blue
    purple:
      primary-color: purple
    orange:
      primary-color: orange
 
coinbase:
  api_key: !secret cb_key
  api_secret: !secret cb_secret
  exchange_rate_currencies:
    - BTC
    - ETH
    - LTC

sun:

map:

zone: !include zones.yaml

usps:
  username: !secret usps_username
  password: !secret usps_password

device_tracker:
  - platform: gpslogger
    icon: mdi:android
    password: !secret gpspass

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://127.0.0.1:3218
  ide:
    title: IDE
    icon: mdi:code-braces
    url: http://127.0.0.1:80
    
notify:
  - platform: pushbullet
    name: pb
    api_key: !secret pushbullet_api

switch: 
  - platform: tplink
    host: 192.168.0.58
    name: TPLink
  - platform: hook
    name: Hook
    token: !secret hook_token

camera:
  - platform: rpi_camera
    name: RaspberryPi Cam
    vertical_flip: 1
    horizontal_flip: 1
    image_quality: 5
    #file_path: /tmp/camera.jpg
  - platform: usps
    scan_interval: 10

weblink:
  entities:
    - name: Remote Home Router
      url: https://75.1.37.24:21747/
    - name: HomeAssistant.io
      url: https://home-assistant.io
    - name: NodeMCU
      url: http://dhahaj.duckdns.org:8888/
    - name: IDE
      url: http://dhahaj.duckdns.org/ide.html

android_ip_webcam:
  - host: 192.168.0.166
    port: 8080
    name: AndroidWebCam
    scan_interval: 10
    sensors:
      - audio_connections
      - battery_level
      - motion
    switches:
      - focus
      - night_vision
      - overlay
      - torch
      - video_recording
    # motion_sensor:
