homeassistant:
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 200
  name: Home
  unit_system: imperial
  time_zone: America/Chicago
  temperature_unit: F
  customize: !include customize.yaml

config:

hassio:

automation: !include automations.yaml

http:
  api_password: !secret http_password
  base_url: http://dhahaj.duckdns.org:8123/
  use_x_forwarded_for: True

recorder:
  purge_keep_days: 2

#discovery:
# shopping_list:

updater:
  include_used_components: true

history:

logger:
  default: error
  logs:
    homeassistant.components.switch.hook: debug

# logbook: !include logbook.yaml

frontend:
  themes:
    greeny:
      primary-color: green
    black:
      primary-color: black
    bluesky:
      primary-color: blue
    purple:
      primary-color: purple
    orange:
      primary-color: orange
 
coinbase:
  api_key: !secret cb_key
  api_secret: !secret cb_secret
  exchange_rate_currencies:
    - BTC
    - BCH
    - ETH
    - LTC

sun:
map:
zone: !include zones.yaml

device_tracker:
  - platform: gpslogger
    icon: mdi:android
    password: !secret gpspass

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: http://dhahaj.duckdns.org:8321
    # url: http://192.168.0.194:8321
  sincos:
    title: SinCos
    icon: mdi:buddhism
    url: https://www.openprocessing.org/sketch/544500#
  router_remote:
    title: TP-Link
    icon: mdi:access-point-network
    url: http://dhahaj.duckdns.org:9090
    
notify:
  - platform: pushbullet
    name: pb
    api_key: !secret pushbullet_api

switch: 
  - platform: tplink
    host: 192.168.0.173
    name: HS100
  - platform: hook
    name: Hook
    token: !secret hook_token
  - platform: rpi_gpio
    ports:
      18: pin18

binary_sensor:
  - platform: rpi_gpio
    pull_mode: DOWN
   # invert_logic: false
    ports:
     3: pin3
    
weblink:
  entities:
    - name: Remote Home Router
      url: https://75.1.37.24:21747/
    - name: HomeAssistant.io
      url: https://home-assistant.io
    - name: NodeMCU
      url: http://dhahaj.duckdns.org:7777/
    - name: Archer-C9
      url: http://dhahaj.duckdns.org:9090/
    # - name: IDE
    #   url: http://dhahaj.duckdns.org/ide.html

alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    pending_time: 60
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 30
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30

panel_custom:
  - name: react
    sidebar_title: Example Panel
    sidebar_icon: mdi:checkbox-marked-outline
    # url_path: todomvc
    config:
      title: Wow hello!

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

# mqtt:
  # broker: 192.168.0.104
  # client_id: 123456789
  
# camera:
#   - platform: rpi_camera
#     name: RaspberryPi Cam
#     vertical_flip: 1
#     horizontal_flip: 1
#     image_quality: 5
    #file_path: /tmp/camera.jpg
    #  - platform: usps
    #scan_interval: 10

# panel_iframe:
#   configurator:
#     title: Configurator
#     icon: mdi:wrench
#     url: http://127.0.0.1:3218

# sensor:
#   platform: example

#usps:
# username: !secret usps_username
#  password: !secret usps_password

      #android_ip_webcam:
      #  - host: 192.168.0.166
      #    port: 8080
      #    name: AndroidWebCam
      #    scan_interval: 10
      #    sensors:
      #      - audio_connections
      #      - battery_level
      #      - motion
      #    switches:
      #      - focus
      #      - night_vision
      #      - overlay
      #      - torch
      #      - video_recording
    # motion_sensor: